networks:
  appnetwork:
volumes:
  postgres_data:
services:
  web:
    image: image_aiohttp:1.0
    ports:
      - "8080:8080"
    command: sh -c "sleep 10 && alembic upgrade head && python main.py"
    depends_on:
      - db
    networks:
      - appnetwork

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    env_file:
      db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u admin -d stocks_products_db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnetwork
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - appnetwork   